[[redirects]]
  from = "https://www.csgo-demos-manager.com/map-veto"
  to = "https://csgomapveto.csgo-demos-manager.com"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
